config/routes.rb
Rails.application.routes.draw do
  root 'squirrels#index'


  resources :squirrels

  resources :users
  # resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

 get '/squirrel-hats', to: 'squirrels#squirrel_hats'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/squirrel.rb
class Squirrel < ApplicationRecord
end

app/models/tree.rb
class Tree < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery with: :exception

  private
  def verify_logged_in
    current_user || false
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      log_in(user)
      flash[:notice] = "Hello #{user.username}!"
      redirect_to user_url(user)
    else
      flash[:error] = "Username or password was incorrect"
      render :new
    end
  end

  def destroy
    if user = User.find_by_id(session[:user_id])
      log_out
      flash[:notice] = "So long, #{user.username}"
      redirect_to root_url
    else
      flash[:error] = "You somehow failed to log out"
      redirect_to user_path(user)
    end
  end
end

app/controllers/squirrels_controller.rb
class SquirrelsController < ApplicationController
  def index
    @squirrels = Squirrel.all
  end

  def show
    @squirrel = Squirrel.find(params[:id])
    @tree = Tree.find(params[:tree_id])
  end

  def new
    @squirrel = Squirrel.new
  end

  private
  def squirrel_params
    params.require(:squirrel).permit(:name, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:index, :new, :create]
  before_action :authorize_user, only: [:edit, :update, :delete]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Welcome, #{@user.username}!"
      redirect_to @user
    else
      render :new
    end
  end

  def update
    if @user = User.find(params[:id])
      @user.update_attributes(user_params)
      flash[:success] = "#{@user.username}"
      redirect_to @user
    else
      flash[:error] = "User error"
      render :edit
    end
  end

  def destroy
    @user.delete
    log_out @user
    redirect_to root_url
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

  def set_user
    unless @user = User.find_by_id(params[:id])
      flash[:error] = "User with id #{params[:id]} does not exist"
      redirect_to root_url
    end
  end

  def authorize_user
    unless params[:id] == session[:user_id]
      flash[:error] = "You must be logged in"
      redirect_to login_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
  end

  def current_user
    User.find_by_id(session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/views/layouts/_flash.html.erb
<% unless flash.empty? %>
  <div class="flash-container">
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>">
        <%= value %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_nav-bar.html.erb
<nav>
  <div class="title">
    <span class="nav-item"><%= link_to 'squirrels!', root_path %></span>
  </div>
  <div class="menu">
    <ul>
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to 'log out', logout_path, method: :delete %>
        </li>
      <% else %>
        <li class="nav-item"><%= link_to 'log in', login_path %></li>
        <li class="nav-item"><%= link_to 'sign up', new_user_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Squirrels</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav-bar" %>
    <%= render "layouts/flash" %>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/squirrels/index.html.erb
<%= image_tag 'squirrel.jpg' %>
<%# link_to 'click here', tree_squirrel_path(@tree, 1) %>

app/views/squirrels/show.html.erb
<%= @squirrel.name %>

app/views/squirrels/squirrel_hats.html.erb
Squirrels love hats

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
I'm a users controller

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div class="content">
  <div>
    <%= @user.username %>
  </div>

  <div>
    <%= link_to "Delete this user", logout_path, method: :delete %>
  </div>

</div>